openapi: "3.0.0"
info:
  version: 1.0.0
  title: BTC Exchange
paths:
  /register:
    post:
      summary: Register a new account
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '200':
          description: Registration result
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
  /balance:
    post:
      summary: Deposit account
      operationId: postBalance
      security:
        - TokenAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                topupAmount:
                  type: string
                currency:
                  type: string
              required:
                - topupAmount
                - currency
      responses:
        '200':
          description: Response with confirmation of deposit
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                required:
                  - success
    get:
      summary: Get balance
      operationId: getBalance
      security:
        - TokenAuth: [ ]
      responses:
        '200':
          description: Response with balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  USD:
                    type: string
                  BTC:
                    type: string
                  USDEquivalent:
                    type: string
                required:
                  - USD
                  - BTC
                  - USDEquivalent
components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: X-Token