// Code generated by sqlc. DO NOT EDIT.

package testqueries

import (
	"database/sql"
	"fmt"
)

type OrderState string

const (
	OrderStateLive      OrderState = "live"
	OrderStateFulfilled OrderState = "fulfilled"
	OrderStateCancelled OrderState = "cancelled"
)

func (e *OrderState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderState(s)
	case string:
		*e = OrderState(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderState: %T", src)
	}
	return nil
}

type OrderType string

const (
	OrderTypeBuy  OrderType = "buy"
	OrderTypeSell OrderType = "sell"
)

func (e *OrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderType(s)
	case string:
		*e = OrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderType: %T", src)
	}
	return nil
}

type Account struct {
	ID        int32
	Username  string
	Token     string
	UsdAmount int64
	BtcAmount int64
}

type StandingOrder struct {
	ID                int32
	AccountID         int32
	Type              OrderType
	State             OrderState
	Quantity          int64
	FilledQuantity    int64
	FilledPrice       int64
	LimitPrice        int64
	ReservedUsdAmount int64
	ReservedBtcAmount int64
	WebhookUrl        sql.NullString
}
