// Code generated by sqlc. DO NOT EDIT.

package queries

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateStandingOrder(ctx context.Context, arg CreateStandingOrderParams) (StandingOrder, error)
	DeleteStandingOrder(ctx context.Context, id int32) error
	GetAccountById(ctx context.Context, id int32) (Account, error)
	GetAccountByToken(ctx context.Context, token string) (Account, error)
	GetBestBuyer(ctx context.Context, limitPrice int64) (StandingOrder, error)
	GetBestMarketBuyer(ctx context.Context) (StandingOrder, error)
	GetBestMarketSeller(ctx context.Context) (StandingOrder, error)
	GetBestSeller(ctx context.Context, limitPrice int64) (StandingOrder, error)
	GetReservedAmounts(ctx context.Context, accountID int32) (GetReservedAmountsRow, error)
	GetStandingOrder(ctx context.Context, id int32) (StandingOrder, error)
	GetStandingOrders(ctx context.Context, orderIds []int32) ([]StandingOrder, error)
	InsertAccountForTest(ctx context.Context, arg InsertAccountForTestParams) (Account, error)
	InsertStandingOrderForTest(ctx context.Context, arg InsertStandingOrderForTestParams) (StandingOrder, error)
	SatisfyOrder(ctx context.Context, arg SatisfyOrderParams) (StandingOrder, error)
	SelectAccountsForTest(ctx context.Context) ([]Account, error)
	SelectStandingOrdersForTest(ctx context.Context) ([]StandingOrder, error)
	TransferAmounts(ctx context.Context, arg TransferAmountsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
